### ISSUE TITLE
Script(translate) execution failure

### ISSUE THREAD

**Issue by roflsunriz** [nonnonstop/apimater#4]
Environment
===========
Platform:Android
OS Version:12
Testing Software Version:APIMateR
0.6.0
Chmate 0.8.10.153
Device Models:Aquos R5G SH-51A

Description
===========
Executing APIMateR command from chmate menu it shows error like "Script(translate) execution failure". It shows same error for every dat-lost threads so we need to renew its script to adjust 5ch's new specification of threads.

Steps to reproduce
==================
1.Open a thread for you want to read inside ChMate
2.Run APIMateR command from ⋮ menu
3.You will see error

Expected result
===============
Translates web to dat as expected

Actual result
=============
Error

Reproducibility Rate
====================
Always

Workarounds
===========
Edit scripts I guess?

Severity (Reference)
====================
Critical

Priority (Reference)
====================
High

Screenshots / Videos / Logs
===========================
![Screenshot_20221216-222217](https://user-images.githubusercontent.com/8847851/208108626-51adcf0b-1b6b-40b0-8b8e-0bc9a417c181.png)

Notes
=====
Thanks for great app. I searched internet then I found there was an app called DatMate existed beforehand APIMate.

Used <a href="https://github.com/roflsunriz/Github-Bug-Report-Text-Template">Github Bug Report Text Template</a> to make this report!

**Comment by nonnonstop** [comment]
thank you for reporting!
send me the logs in `/storage/emulated/0/Android/data/com.nonnonstop.apimate/`

**Comment by roflsunriz** [comment]
here 
[exception0.txt](https://github.com/nonnonstop/apimater/files/10278278/exception0.txt)

**Comment by nonnonstop** [comment]
Try selecting the dat directory in the settings screen.

**Comment by roflsunriz** [comment]
Ah yeah. It's working.
The problem caused was mainly due to introduced blocking storage by newer Android.
Maybe it is good idea that add notification for that need to grant permission?
