### ISSUE TITLE
Date/IP becomes NG/NG in Siberia

### ISSUE THREAD

**Issue by roflsunriz** [nonnonstop/apimater#5]
Environment
===========
Platform:Android
OS Version:8.1,12,13
Testing Software Version:APIMateR
0.6.0
Chmate 0.8.10.153
Device Models:Huawei P20 Pro HW-01K(8.1),Aquos R5G SH-51A(12),Google Pixel 6a(13)

Description
===========
Date and IP addresses becomes NG and NG string in translated dat file in [シベリア超速報（siberia）](https://pug.5ch.net/siberia/). I suspect that it is because of dat translation was mechanical and process is not suit for siberia.

Steps to reproduce
==================
1.Open a thread for you want to read inside ChMate
2.Run APIMateR command from ⋮ menu
3.You will NG string instead of date and IP addresses

Expected result
===============
Right date and IP

Actual result
=============
string NG is in dat

Reproducibility Rate
====================
Always

Workarounds
===========
None

Severity (Reference)
====================
Low

Priority (Reference)
====================
Medium

Screenshots / Videos / Logs
===========================
![Point Blur_20221222_080522](https://user-images.githubusercontent.com/8847851/209024542-93349e8d-4153-4db9-a5a4-0be4dfcd1bea.png)

Notes
=====

Used <a href="https://github.com/roflsunriz/Github-Bug-Report-Text-Template">Github Bug Report Text Template</a> to make this report!

**Comment by nonnonstop** [comment]
The reason is that the date and ID are "NG" when a post is retrieved from html.
![image](https://user-images.githubusercontent.com/42905588/210159382-3eb75696-be29-4e1b-9642-497fe8f3bd66.png)
I don't know how to fix it as it's a 5ch issue.

**Comment by roflsunriz** [comment]
Can you use smartphone version page instead for PC version? In the smartphone version it shows normal.

**Comment by nonnonstop** [comment]
thank you! I found itest API.
I'll add itest translator in the next version.

**Comment by roflsunriz** [comment]
Geez! That's nice. I can't wait for that.

**Comment by nonnonstop** [comment]
i've added a new translator in v0.7.0, try it.

**Comment by roflsunriz** [comment]
thanks! working! string "発信元:" isn't needed tho

**Comment by nonnonstop** [comment]
I'll fix it later. thanks

**Comment by nonnonstop** [comment]
fixed in v0.7.1

**Comment by roflsunriz** [comment]
Thanks!
