### ISSUE TITLE
Bbspink translation failure

### ISSUE THREAD

**Issue by roflsunriz** [nonnonstop/apimater#6]
Environment
===========
Platform:Android
OS Version:13
Testing Software Version:APIMateR 0.6.0
Chmate 0.8.10.153
Device Models:Google Pixel 6a

Description
===========
Translation fails at bbspink

Steps to reproduce
==================
1. open dat lost thread
2. run apimater
3. see error

Expected result
===============
translation success

Actual result
=============
error

Reproducibility Rate
====================
Always

Workarounds
===========
Unknown

Severity (Reference)
====================
High

Priority (Reference)
====================
High

Screenshots / Videos / Logs
===========================

Notes
=====

Used <a href="https://github.com/roflsunriz/Github-Bug-Report-Text-Template">Github Bug Report Text Template</a> to make this report!

**Comment by roflsunriz** [comment]
It's hard to attach files in mobile
[exception0.txt](https://github.com/nonnonstop/apimater/files/10418532/exception0.txt)

**Comment by nonnonstop** [comment]
thank you for reporting.
please provide url.

**Comment by roflsunriz** [comment]
Any url, for example
https://mercury.bbspink.com/test/read.cgi/adultsite/1655279326/

**Comment by nonnonstop** [comment]
It works for me.
Your IP address may be blocked. The log shows that server returned "410 Gone" response.

**Comment by roflsunriz** [comment]
umm, confirmed.
I can show itest page but pc version says 410 Gone.
Probably there's nothing to do with apimater

**Comment by roflsunriz** [comment]
reconnect did the trick
