### ISSUE TITLE
一部のレスが欠落したdatを作成してしまう事がある

### ISSUE THREAD

**Issue by JohnSmith774** [nonnonstop/apimater#7]
例えば完走して総レス数が1002のスレの場合、APIMateR(0.7.1)で開くと総レス数が1001以下に減っている

以下のスレを含む、2015～2016年頃の携帯ゲームソフト板の複数のスレで発生を確認

【3DS】ニンテンドーeShop総合Part129【eショップ】 [無断転載禁止]©2ch.net
https://wktk.5ch.net/test/read.cgi/handygame/1449846184/

総レス数は1002だがAPIMateRを通すと961レスしか取得できてない
上記スレでは少なくとも>>21, >>139, >>157, >>184のレスがないことを確認済み（ウェブブラウザで開くと元のレスが見れる）
共通点はいずれもメール欄が空欄
メール欄が空欄のレスは変換の際にスキップされてる？（未検証）

**Comment by nonnonstop** [comment]
報告ありがとうございます。

* 設定画面のトランスレーター・スクリプトの内容を添付してください。
* `/storage/emulated/0/Android/data/com.nonnonstop.apimate/` にあるログファイルを添付してください。

**Comment by JohnSmith774** [comment]
- トランスレーター・スクリプトです
[トランスレータースクリプト.txt](https://github.com/nonnonstop/apimater/files/11303867/default.txt)
- ログファイルとしてexception0.txtを添付しようと思ったのですが、誤って削除してしまいました。すみません。
報告したURL含む事象が発生したスレで再度APIMateRを使用したら同じようなログが採取できると思い
今しがた同じスレを取得したのですが1002レス全て読み込めていました。頭の中が「？？？」で一杯です。

**Comment by nonnonstop** [comment]
ありがとうございます。5ch側の一時的な問題の可能性のようなのでクローズします。
